<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0sxgSxp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0sxgSxp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0sxgSxp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0sxgSxp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container0sxgSxp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '0sxgSxp',
    'container.build_id' => '7d49d6b7',
    'container.build_time' => 1628535511,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0sxgSxp');
